version: '2'
services:
  alpine-webdav:
    build:
      context: .
    restart: always
    ports:
      - 8888:80
    volumes:
      - ./foo:/var/webdav
    environment:
      - USERNAME=foo
      - PASSWORD=bar
    logging:
      options:
        max-size: "10m"
        max-file: "2"

